// Code generated by "stringer -type EStatus,EPaymentType,ETransactionType -output enums.go"; DO NOT EDIT

package transactions

import "fmt"

const _EStatus_name = "SUCCESSFULCANCELLEDFAILED"

var _EStatus_index = [...]uint8{0, 10, 19, 25}

func (i EStatus) String() string {
	if i < 0 || i >= EStatus(len(_EStatus_index)-1) {
		return fmt.Sprintf("EStatus(%d)", i)
	}
	return _EStatus_name[_EStatus_index[i]:_EStatus_index[i+1]]
}

const _EPaymentType_name = "CASHPOSECOMBITCOINBALANCE"

var _EPaymentType_index = [...]uint8{0, 4, 7, 11, 18, 25}

func (i EPaymentType) String() string {
	if i < 0 || i >= EPaymentType(len(_EPaymentType_index)-1) {
		return fmt.Sprintf("EPaymentType(%d)", i)
	}
	return _EPaymentType_name[_EPaymentType_index[i]:_EPaymentType_index[i+1]]
}

const _ETransactionType_name = "PAYMENTREFUNDCHARGE_BACK"

var _ETransactionType_index = [...]uint8{0, 7, 13, 24}

func (i ETransactionType) String() string {
	if i < 0 || i >= ETransactionType(len(_ETransactionType_index)-1) {
		return fmt.Sprintf("ETransactionType(%d)", i)
	}
	return _ETransactionType_name[_ETransactionType_index[i]:_ETransactionType_index[i+1]]
}
